version: '2'

services:
  django:
    build: .
    volumes:
      - ./:/code
    ports:
      - "8000:8000"
    command: python3 manage.py runserver 0.0.0.0:8000
    restart: unless-stopped
    expose:
      - '8000'

  frontend:
    build: ./frontend
    volumes:
      - ./frontend/app:/app
    ports:
      - "8181:8181"
    command: python3 -m http.server 8181
    expose:
      - '8181'
  
