version: '2'

services:
  django:
    build: .
    volumes:
      - ./:/code
    ports:
      - "8000:8000"
    command: uwsgi --http :8000 --module flash_monitor_project.wsgi
    restart: unless-stopped
    expose:
      - '8000'

  frontend:
    build: ./frontend
    volumes:
      - ./frontend/app:/app
    ports:
      - "8181:8181"
    command: python3 -m http.server 8181
    expose:
      - '8181'
  
  nginx:
    image: nginx
    restart: always
    volumes:
      - .:/app
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
      - "443:443"
    links:
        - django
        - frontend
