# Generated by Django 2.1 on 2019-03-10 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0002_auto_20190309_1536'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchAdvise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schema', models.TextField()),
            ],
        ),
    ]
