# Generated by Django 2.1 on 2019-03-09 15:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='alert_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitor.AlertStatus'),
        ),
        migrations.AlterField(
            model_name='alert',
            name='body_type',
            field=models.ManyToManyField(blank=True, null=True, to='monitor.BodyType'),
        ),
        migrations.AlterField(
            model_name='alert',
            name='control',
            field=models.ManyToManyField(blank=True, null=True, to='monitor.Control'),
        ),
        migrations.AlterField(
            model_name='alert',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='alert',
            name='finish_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='alert',
            name='unit',
            field=models.ManyToManyField(blank=True, null=True, to='monitor.Unit'),
        ),
        migrations.AlterField(
            model_name='application',
            name='has_controls',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='application',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='application',
            name='is_visiable',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='bodytype',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='bodytype',
            name='is_visiable',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='control',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='control',
            name='is_visiable',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='problem',
            name='body_type',
            field=models.ManyToManyField(blank=True, null=True, to='monitor.BodyType'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='control',
            field=models.ManyToManyField(blank=True, null=True, to='monitor.Control'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='unit',
            field=models.ManyToManyField(blank=True, null=True, to='monitor.Unit'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='unit',
            name='is_visiable',
            field=models.BooleanField(default=True),
        ),
    ]
