# Generated by Django 2.1 on 2019-03-10 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0003_auto_20190310_0934'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='controltype',
            name='label',
        ),
    ]
