# Generated by Django 2.1 on 2019-03-10 10:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0004_remove_controltype_label'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitor.Application'),
        ),
        migrations.AlterField(
            model_name='alert',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='problem',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitor.Application'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
