# Generated by Django 2.1 on 2019-03-11 16:50

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0005_auto_20190310_1022'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alert',
            options={'verbose_name': 'Алерт', 'verbose_name_plural': 'Алерты'},
        ),
        migrations.AlterModelOptions(
            name='alertcategory',
            options={'verbose_name': 'Категория алерта', 'verbose_name_plural': 'Категории алертов'},
        ),
        migrations.AlterModelOptions(
            name='alertstatus',
            options={'verbose_name': 'Статус алерта', 'verbose_name_plural': 'Статусы алертов'},
        ),
        migrations.AlterModelOptions(
            name='application',
            options={'verbose_name': 'Приложение', 'verbose_name_plural': 'Приложения'},
        ),
        migrations.AlterModelOptions(
            name='bodytype',
            options={'verbose_name': 'Тип кузова', 'verbose_name_plural': 'Типы кузова'},
        ),
        migrations.AlterModelOptions(
            name='control',
            options={'verbose_name': 'Блок управления', 'verbose_name_plural': 'Блоки управления'},
        ),
        migrations.AlterModelOptions(
            name='problem',
            options={'verbose_name': 'Проблема', 'verbose_name_plural': 'Проблемы'},
        ),
        migrations.AlterModelOptions(
            name='problemstatus',
            options={'verbose_name': 'Статус проблемы', 'verbose_name_plural': 'Статусы проблем'},
        ),
        migrations.AlterModelOptions(
            name='unit',
            options={'verbose_name': 'Агрегат', 'verbose_name_plural': 'Агрегаты'},
        ),
        migrations.RemoveField(
            model_name='control',
            name='control_type',
        ),
        migrations.AddField(
            model_name='control',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='alert',
            name='alert_type',
            field=models.ForeignKey(default='ACTIVE', on_delete=django.db.models.deletion.CASCADE, to='monitor.AlertStatus'),
        ),
        migrations.AlterField(
            model_name='alert',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2019, 3, 11, 16, 50, 45, 943916)),
        ),
        migrations.AlterField(
            model_name='problem',
            name='detection_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 11, 16, 50, 45, 947493)),
        ),
        migrations.AlterField(
            model_name='problem',
            name='status',
            field=models.ForeignKey(default='NEW', null=True, on_delete=django.db.models.deletion.SET_NULL, to='monitor.ProblemStatus'),
        ),
        migrations.DeleteModel(
            name='ControlType',
        ),
    ]
