# Generated by Django 2.1 on 2019-03-13 03:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0006_auto_20190311_1650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='problem',
            name='detection_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
