# Generated by Django 2.1 on 2019-03-16 05:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0007_auto_20190316_0401'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='controltype',
            options={'verbose_name': 'Тип блока управления', 'verbose_name_plural': 'Тип блока управления'},
        ),
        migrations.AlterField(
            model_name='alert',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 16, 5, 24, 28, 287096), verbose_name='Дата начала'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='detection_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 16, 5, 24, 28, 290682), verbose_name='Дата и время обнаружения'),
        ),
    ]
