# Generated by Django 2.1 on 2019-03-14 09:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0007_auto_20190313_0351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='alert_type',
            field=models.ForeignKey(default='ACTIVE', on_delete=django.db.models.deletion.CASCADE, to='monitor.AlertStatus', verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='alert',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitor.Application', verbose_name='Приложение'),
        ),
        migrations.AlterField(
            model_name='alert',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='alert',
            name='body_type',
            field=models.ManyToManyField(blank=True, null=True, to='monitor.BodyType', verbose_name='Типы кузова'),
        ),
        migrations.AlterField(
            model_name='alert',
            name='category',
            field=models.ForeignKey(default='APPLICATION_ALERT', on_delete=django.db.models.deletion.CASCADE, to='monitor.AlertCategory', verbose_name='Категория алерта'),
        ),
        migrations.AlterField(
            model_name='alert',
            name='control',
            field=models.ManyToManyField(blank=True, null=True, to='monitor.Control', verbose_name='Блоки управления'),
        ),
        migrations.AlterField(
            model_name='alert',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='alert',
            name='finish_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата окончания(план)'),
        ),
        migrations.AlterField(
            model_name='alert',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Дата начала'),
        ),
        migrations.AlterField(
            model_name='alert',
            name='unit',
            field=models.ManyToManyField(blank=True, null=True, to='monitor.Unit', verbose_name='Агрегаты'),
        ),
        migrations.AlterField(
            model_name='application',
            name='has_controls',
            field=models.BooleanField(default=False, verbose_name='Наличие блоков управления'),
        ),
        migrations.AlterField(
            model_name='application',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Иконка'),
        ),
        migrations.AlterField(
            model_name='application',
            name='is_visiable',
            field=models.BooleanField(default=True, verbose_name='Отображать для клиента'),
        ),
        migrations.AlterField(
            model_name='application',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='bodytype',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Иконка'),
        ),
        migrations.AlterField(
            model_name='bodytype',
            name='is_visiable',
            field=models.BooleanField(default=True, verbose_name='Отображать для клиента'),
        ),
        migrations.AlterField(
            model_name='bodytype',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='control',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Иконка'),
        ),
        migrations.AlterField(
            model_name='control',
            name='is_visiable',
            field=models.BooleanField(default=True, verbose_name='Отображать для клиента'),
        ),
        migrations.AlterField(
            model_name='control',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='alert',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='monitor.Alert', verbose_name='Алерт'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitor.Application', verbose_name='Приложение'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='body_type',
            field=models.ManyToManyField(blank=True, null=True, to='monitor.BodyType', verbose_name='Типы кузова'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='control',
            field=models.ManyToManyField(blank=True, null=True, to='monitor.Control', verbose_name='Блоки управления'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='detection_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата и время обнаружения'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='status',
            field=models.ForeignKey(default='NEW', null=True, on_delete=django.db.models.deletion.SET_NULL, to='monitor.ProblemStatus', verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='unit',
            field=models.ManyToManyField(blank=True, null=True, to='monitor.Unit', verbose_name='Агрегаты'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Иконка'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='is_visiable',
            field=models.BooleanField(default=True, verbose_name='Отображать для клиента'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Название'),
        ),
    ]
