# Generated by Django 2.1 on 2019-03-14 09:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0008_auto_20190314_0955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='start_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата начала'),
        ),
    ]
