# Generated by Django 2.1 on 2019-03-27 22:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0011_auto_20190324_1508'),
    ]

    operations = [
        migrations.RenameField(
            model_name='controltype',
            old_name='icon',
            new_name='image',
        ),
        migrations.AlterField(
            model_name='alert',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 27, 22, 54, 2, 861347), verbose_name='Дата начала'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='detection_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 27, 22, 54, 2, 865023), verbose_name='Дата и время обнаружения'),
        ),
    ]
